language: go

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx
  - windows  

before_install:
  - go get -v ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)